### ISSUE TITLE
关于AdminLTE后台模板的问题

### ISSUE THREAD

**Issue by yinhuanyi** [leffss/devops#11]
你好，我觉得使用AdminLTE做前台模板是不是太冗余了，我觉得可以使用LayUI，或者Vue.js + Element UI这样的会更好一些

**Comment by leffss** [comment]
1. 使用 adminlte 主要是懒
2. 使用 vue.js + element ui 的话又要去学它们，学不完啦，还是懒

反正目前就是主要实现功能，界面随便啦
