### ISSUE TITLE
请问调度主机的功能，如何增加？

### ISSUE THREAD

**Issue by sislcb** [leffss/devops#12]
主机已经有很多台，点击【调度主机】，看到列表是空的。

不清楚这个功能要怎么使用？谢谢。

**Comment by leffss** [comment]
> 主机已经有很多台，点击【调度主机】，看到列表是空的。
> 
> 不清楚这个功能要怎么使用？谢谢。

![image](https://user-images.githubusercontent.com/49055524/80596713-62a62700-8a59-11ea-9c5a-7550ad0f4ea5.png)

这里的列表是真正负责调度任务的主机，会安装一个客户端，是 flask 写的，这个功能估计不会更新完善了。即使做也会单独做一个调度平台，用 go 语言，不会用 python
