### ISSUE TITLE
celery_beat 定时任务处理进程占用内存吗？

### ISSUE THREAD

**Issue by GeniusZhang7** [leffss/devops#13]
一直在后台向celery_beat.log 输入no next task found，这个是否耗比较大的内存
还有就是log日志有的时候更新，有的时候不更新，您有遇到过这种现象吗？

**Comment by leffss** [comment]
这个 no next task found 不占运行内存的，就是个日志输出，只会增加日志文件容量而已，如果不想它输出，可以把相应的日志输出代码注释就可以了

还有就是log日志有的时候更新，有的时候不更新，这个是什么情况，说具体点呢

**Comment by leffss** [comment]
这个项目目前主要是在于功能的实现，我也是现学现做，想到什么就做什么，有点地方可能暂时没有考虑到代码的合理性和性能的需求，这个后期可以优化

**Comment by GeniusZhang7** [comment]
一开始我部署到服务器上，日志可以获取到。然后第二天之后再登录到网站上，日志就没有更新了。我换了一台虚拟机上部署，环境一致，但日志整个模块还是不显示数据。这个业务的代码我没动，而且我检查后也没有问题，可能是我眼拙。
