### ISSUE TITLE
请问支持Windows和saltstack吗

### ISSUE THREAD

**Issue by xiaohuazi123** [leffss/devops#15]
请问支持Windows和saltstack吗

**Comment by leffss** [comment]
> 请问支持Windows和saltstack吗

不太懂什么意思？

**Comment by xiaohuazi123** [comment]
这个系统支持 管理windows吗？

**Comment by leffss** [comment]
可以远程桌面登录windows，上传下载文件都可以，批量管理不行

**Comment by xiaohuazi123** [comment]
> 可以远程桌面登录windows，上传下载文件都可以，批量管理不行



堡垒机的功能而已，但是自动化运维windows不行

**Comment by leffss** [comment]
> > 可以远程桌面登录windows，上传下载文件都可以，批量管理不行
> 
> 堡垒机的功能支持windows和Linux，但是自动化运维windows不行，是不是这个意思？请问

你理解的自动化运维是什么？

**Comment by xiaohuazi123** [comment]
> > > 可以远程桌面登录windows，上传下载文件都可以，批量管理不行
> > 
> > 
> > 堡垒机的功能支持windows和Linux，但是自动化运维windows不行，是不是这个意思？请问
> 
> 你理解的自动化运维是什么？



就是能自动在Windows机器上执行一些运维操作，比如自动添加 计划任务，自动启停 Windows服务等等
