### ISSUE TITLE
建议加个多服务器节点，这样就完美了

### ISSUE THREAD

**Issue by wg1929** [leffss/devops#17]
比如要连接法国的服务器，可以选择某个节点速度更快

**Comment by leffss** [comment]
> 比如要连接法国的服务器，可以选择某个节点速度更快

很好的建议，但是要实现分布式节点才行，改动很大

**Comment by leffss** [comment]
这个 python 版本的不考虑分布式节点了，因为改动太大；准备重构为 go 版本的，一开始就会考虑分布式节点的问题的
