### ISSUE TITLE
docker 部署

### ISSUE THREAD

**Issue by wenwenxiong** [leffss/devops#18]
能不能给出一个docker部署方案，可以快速部署起来熟悉功能，用docker-compose管理起来，类似opsmanage项目那样https://github.com/welliamcao/OpsManage/tree/v3/docker

**Comment by leffss** [comment]
> 能不能给出一个docker部署方案，可以快速部署起来熟悉功能，用docker-compose管理起来，类似opsmanage项目那样https://github.com/welliamcao/OpsManage/tree/v3/docker

好建议，等空闲的时候整个docker或者docker-compose部署的吧

**Comment by leffss** [comment]
> 能不能给出一个docker部署方案，可以快速部署起来熟悉功能，用docker-compose管理起来，类似opsmanage项目那样https://github.com/welliamcao/OpsManage/tree/v3/docker

其实代码里面有dockerfile，你可以简单修改一下做成 docker-compose 的

**Comment by leffss** [comment]
> 能不能给出一个docker部署方案，可以快速部署起来熟悉功能，用docker-compose管理起来，类似opsmanage项目那样https://github.com/welliamcao/OpsManage/tree/v3/docker

其实代码里面有dockerfile，你可以简单修改一下做成 docker-compose 的
