### ISSUE TITLE
用mysql报的错

### ISSUE THREAD

**Issue by alongkim** [leffss/devops#5]
django.db.migrations.exceptions.NodeNotFoundError: Migration user.0010_auto_20190907_1653 dependencies reference nonexistent parent node ('user', '0009_auto_20190907_1641')

**Comment by alongkim** [comment]
想问下，这个会是什么问题呢

**Comment by leffss** [comment]
迁移数据库错误，建议你按照说明一步一步执行：
```
sh delete_makemigrations.sh
rm -f db.sqlite3
python3 manage.py makemigrations
python3 manage.py migrate
```

**Comment by alongkim** [comment]
> 迁移数据库错误，建议你按照说明一步一步执行：
> 
> ```
> sh delete_makemigrations.sh
> rm -f db.sqlite3
> python3 manage.py makemigrations
> python3 manage.py migrate
> ```
是按照这个执行，第一步就出错了

**Comment by xayle** [comment]
> > 迁移数据库错误，建议你按照说明一步一步执行：
> > ```
> > sh delete_makemigrations.sh
> > rm -f db.sqlite3
> > python3 manage.py makemigrations
> > python3 manage.py migrate
> > ```
> 
> 是按照这个执行，第一步就出错了

delete_makemigrations.sh 这个文件中 **000** 改成 **00**
```
#!/bin/bash
cd apps
lists=$(ls)
for i in $lists;do
	rm -f $i/migrations/00*.py
done
```

**Comment by leffss** [comment]
> > > 迁移数据库错误，建议你按照说明一步一步执行：
> > > ```
> > > sh delete_makemigrations.sh
> > > rm -f db.sqlite3
> > > python3 manage.py makemigrations
> > > python3 manage.py migrate
> > > ```
> > 
> > 
> > 是按照这个执行，第一步就出错了
> 
> delete_makemigrations.sh 这个文件中 **000** 改成 **00**
> 
> ```
> #!/bin/bash
> cd apps
> lists=$(ls)
> for i in $lists;do
> 	rm -f $i/migrations/00*.py
> done
> ```

已修正为：
```bash
#!/bin/bash

cd apps

lists=$(ls)
for i in $lists;do
	ls -d $i/migrations/* | grep -v '__init__.py' | xargs rm -rf
done

```
